### PR TITLE
[cli] Update README.md

### PR DESCRIPTION
**Pull request by Johannes7k75**
## Description

Changes the name of the docker image that gets build.

### CODE REVIEW

**Comment by ua741** [comment]
Hey, thank you for the PR. Can you please update the other commands  in README, where we are still referencing to ente-cli.

**Comment by ua741** [comment]
Hey @johannes7k75 ,
After discussing it internally, we are a bit reluctant to implement this change as it’s a breaking change for existing users with limited benefits. I understand why you proposed the change, but for now, we will put it on hold and address it alongside any future breaking changes.

**Comment by Johannes7k75** [comment]
I understand but one thing should be changed.
The docker build command to
`docker build -t ente-cli:latest .`
or the User has to Change it himself. Because the docker Composer ist using the `ente-cli:latest` image

**Comment by Johannes7k75** [comment]
Should i create a new PR for the change
> `docker build -t ente-cli:latest .`

or change the commits from here

**Comment by Johannes7k75** [comment]
Or combine docker build and docker compose?

like `docker compose up -d --build`

```diff
# cli/docker-compose.yaml
services:
  ente-cli:
+   build:
+     context: .
+     tags:
+       - ente-cli:latest
  command: /bin/sh      
```

**Comment by ua741** [comment]
> Or combine docker build and docker compose?
> 
> like `docker compose up -d --build`
> 
> ```diff
> # cli/docker-compose.yaml
> services:
>   ente-cli:
> +   build:
> +     context: .
> +     tags:
> +       - ente-cli:latest
>   command: /bin/sh      
> ```
Make sense.
Can you please update the PR with this change.

**Comment by Johannes7k75** [comment]
> > Or combine docker build and docker compose?
> > like `docker compose up -d --build`
> > ```diff
> > # cli/docker-compose.yaml
> > services:
> >   ente-cli:
> > +   build:
> > +     context: .
> > +     tags:
> > +       - ente-cli:latest
> >   command: /bin/sh      
> > ```
> 
> Make sense. Can you please update the PR with this change.

Changes are committed

**Review by ua741 — APPROVED** [review]

**Pull request merged**
