### PR TITLE
Add new icons

### PR DESCRIPTION
**Pull request by LeGenDaRy15PT**
Add new icons

### CODE REVIEW

**Comment by tanguylegazon** [comment]
Hey @LeGenDaRy15PT 👋

That’s quite a bit of work you’ve done!

The Minecraft SVG looks a bit off to me—did you use an image-to-vector converter for it? If so, you might want to try this version instead: https://svgur.com/i/W65.svg (although I haven’t checked for any potential licensing restrictions).

Also, the Steam logo you used is actually the app icon, not the official brand logo. According to the [official branding guidelines](https://steamcdn-a.akamaihd.net/steamcommunity/public/images/steamworks_docs/french/Steam_Guidelines_060222.pdf), the Steam logo should be monochromatic. I’d suggest reverting the changes for this one to follow the guidelines.

Thanks for all the effort!

**Comment by LeGenDaRy15PT** [comment]
Hello @tanguylegazon 👋

I'll make these changes now, thanks for letting me know
You're welcome, whatever I can help with to complete this application, I will do so 👍

**Comment by tanguylegazon** [comment]
It might be preferable to revert to the original setup for the Steam logo by removing `Steam.svg` and the corresponding entry in `custom-icons.json`. This approach would have a few benefits:

- The logo could then be sourced directly from the [simple-icons](https://github.com/simple-icons/simple-icons) library, allowing us to:
  - Avoid duplicates in the repo
  - Skip any maintenance for the logo
- The logo would also automatically adjust to light and dark themes within the app

In general, it’s best to avoid adding a logo to the project if it’s already available in the simple-icons library, follows brand guidelines, and displays well in the Auth app.

**Comment by LeGenDaRy15PT** [comment]
I've already removed the Steam logo

**Comment by redneckeyeball** [comment]
Would it be possible to add this logo ?
https://nl.wikipedia.org/wiki/Bestand:SNCB_logo.svg
Company name SNCB
Thank you !

**Comment by vishnukvmd** [comment]
Hey @LeGenDaRy15PT, unfortunately quite a few of these icons are not getting rendered in-app, so we've had to revert this change to resolve issues.

We'll figure out a way to create a playground so that changes to icons can be tested out.

Thank you for the contribution, and sorry for undoing the changes.

**Pull request merged**
