### PR TITLE
[auth] Refactor, clean and add icons

### PR DESCRIPTION
**Pull request by Eseltwift**
- Clean and refactor JSON file for custom icons
  (It seems that some contributors are misusing the `slug` and `altNames` fields.)
- Fix some icons
- Add Battle.net icon since it doesn't seems to be working with simple-icons (tried `Battle.net`, `Battlenet`, `Blizzard`)

## Type of Change

- [x] 🖼️ New icon
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

**Comment by Eseltwift** [comment]
I hope it doesn't break anything 😅 We're not safe from a little mistake on my part, unfortunately I can't test all the icons.

**Comment by Jetspectre** [comment]
Would it be possible to add [this](https://github.com/ente-io/ente/discussions/3045) to the PR?

**Comment by Eseltwift** [comment]
> Would it be possible to add [this](https://github.com/ente-io/ente/discussions/3045) to the PR?

I'll check that

**Review by Vantesh — COMMENTED** [review]
Great work 👍 i was wondering why bitget wallet icon wasn't showing up 😀 turns out it was just a typo 😅

**Review by ua741 — APPROVED** [review]

**Pull request merged**
