### PR TITLE
Fix cases

### PR DESCRIPTION
**Pull request by vishnukvmd**
## Description
The intent was to lower the case for "Files" and "Each" (that were in caps), since the file was open, also ended up flipping the case for "ente".

## Tests
Have verified the places "files" and "each" were being printed. As for "Ente", the change should not cause any side effects.

### CODE REVIEW

**Comment by mnvr** [comment]
We'll need to manually update the translations. I'll do that after merging this.

**Review by mnvr — APPROVED** [review]

**Comment by mnvr** [comment]
> We'll need to manually update the translations.

In Crowdin I mean.

**Comment by vishnukvmd** [comment]
I thought if the value corresponding to a key changed, Crowdin would expire the older string? 🤔

**Comment by mnvr** [comment]
> I thought if the value corresponding to a key changed, Crowdin would expire the older string?

You're right. But in these cases the rest of the string remains unchanged, and I can save the translators a bunch of work by updating it manually in these cases.

**Pull request merged**
