### PR TITLE
[auth] Added Upstox Icon

### PR DESCRIPTION
**Pull request by AgentT30**
## Description
https://upstox.com/ -> is an online stock broker popular in India

### CODE REVIEW

**Comment by ua741** [comment]
> @ua741 can you please review and merge this?

The icon looks incorrect.

**Comment by AgentT30** [comment]
@ua741 the icon is from the [official website](https://upstox.com/)

**Comment by ua741** [comment]
That's no the official icon. You can see the favicon or the logo on the App/playstore for reference.

**Comment by Eseltwift** [comment]
Indeed, this is the brand's official logotype. But for a use like the one in Ente Auth, we prefer a condensed version of the logo when it exists.

Here's an example with the Rakuten brand:
Example

I'll create a PR with a suitable icon for Upstox.

**Comment by ua741** [comment]
Thank you @AgentT30  & @Eseltwift . This change will be available in the next release (unfortunately, there is no ETA).

**Pull request closed without merging**
